name: Deploy Prefect flow - staging

env:
  PROJECT_NAME: project_2

on:
  push:
    branches:
      - stg
    paths:
      - "$PROJECT_NAME/**"
    paths-ignore:
      - "$PROJECT_NAME/Dockerfile"
      - "$PROJECT_NAME/requirements.txt"

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Prefect Deploy
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_STG_WORKSPACE_URL }}
        run: |
          pip install -r requirements.txt
          prefect deploy --all --prefect-file $PROJECT_NAME/prefect.yaml
