name: Build image and deploy Prefect flow - staging

env:
  PROJECT_NAME: project_2

on:
  push:
    branches:
      - stg
    paths:
      - "$PROJECT_NAME/requirements.txt"
      - "$PROJECT_NAME/Dockerfile"

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get commit hash
        id: get-commit-hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        id: build-docker-image
        env:
          GITHUB_SHA: ${{ steps.get-commit-hash.outputs.COMMIT_HASH }}
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$PROJECT_NAME:$GITHUB_SHA $PROJECT_NAME/
          docker push ${{ secrets.DOCKER_USERNAME }}/$PROJECT_NAME:$GITHUB_SHA
          echo "IMAGE=$(${{ secrets.DOCKER_USERNAME }}/$PROJECT_NAME:$GITHUB_SHA)" >> "$GITHUB_OUTPUT"

      - name: Update image Prefect Variable
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_STG_WORKSPACE_URL }}
          VARIABLE_NAME: $PROJECT_NAME_image
          VARIABLE_VALUE: ${{ steps.build-docker-image.outputs.IMAGE }}
        run: update_variable.sh

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Prefect Deploy
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_STG_WORKSPACE_URL }}
        run: |
          pip install -r requirements.txt
          prefect deploy --all --prefect-file $PROJECT_NAME/prefect.yaml
